### ISSUE TITLE
BLU LUA

### ISSUE THREAD

**Issue by Kagato19987** [ArislanShiva/luas#1]
Several issues in the BLU LUA but namely there are a lot of these in earring slots:

Earing2

Also, don't use Fotia Gorget/Belt for things like Sanguine Blade.

You have sets for BLU magical spells and physical spells but nothing in your mappings file or BLU LUA suggests that these spells have been mapped! This means that these gear sections are completely useless and will not equip unless you actually map them out.

**Comment by ArislanShiva** [comment]
Are you sure you're looking at my lua?  There's in-line mappings for spell types, I'm not seeing any instances of 'earing2' (I use ear1, ear2).

As far as Sanguine Blade, I'd have to test to see if MAB would beat the 3% WSD from Fotias.
