### ISSUE TITLE
BLU Script

### ISSUE THREAD

**Issue by Miltani** [ArislanShiva/luas#10]
Seemed that in the LUA, Voluspa Thathlum are put for all accuracy gears, however BLU cannot equip that item. 
Is there any reason to do this?

**Comment by ArislanShiva** [comment]
That's what can happen when you 'replace all in project' without comparing jobs on items lol. Thanks for bringing it up, I would have never caught it.

**Comment by Miltani** [comment]
No worries, a couple of items like Herc_WS_feet, Herc_WS_hands were removed from your global files but are still kept in the job lua too
