### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by FoxTaco** [ArislanShiva/luas#14]
Just coming back to XI from a long Hiatus. I'm playing BLU and the Herc boots that I've updated the augments on  in the globals lua are not working- am I missing something needed for me to tie in this lua?

**Comment by ArislanShiva** [comment]
Make sure your globals file is named correctly.  It should be YourName_Globals.lua, not Arislan-Globals.lua.

If that's OK, then run a gearswap validatation (type //gs validate in your chat box).  If the piece of gear in question shows up as being missing, then you've entered the augments incorrectly or you've made a mistake in syntax.

**Comment by rareex** [comment]
i have a question may you tell me how to use spell like Etude,Carol,Threnody that Cycle from Ctrl+insert/delete , home/end , pgup/pgdown 
thank you very much your script is very good ^^ will be a lot better if i know how to use them all xD

**Comment by rareex** [comment]
hi again
your RDM lua how to use ACC enfeebling magic set ? ^^;

**Comment by ArislanShiva** [comment]
They are triggered w/ gearswap commands:

//gs c etude
//gs c carol
//gs c threnody

Or you can embed them into macros:

/console gs c etude
/console gs c carol
/console gs c threnody
