### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by stryderxi** [ArislanShiva/luas#15]
First issue is blm spell death won't load elemental belt with dark weather or darksday.

Second issues is cor lua won't load luzaf ring when it is set to on.

**Comment by stryderxi** [comment]
Ok i fixed th blm issue.  Midcast function should look like this

`function job_post_midcast(spell, action, spellMap, eventArgs)
    if spell.skill == 'Enhancing Magic' and classes.NoSkillSpells:contains(spell.english) and not state.DeathMode.value then
        equip(sets.midcast.EnhancingDuration)
        if spellMap == 'Refresh' then
            equip(sets.midcast.Refresh)
        end
    end
    if spell.skill == 'Elemental Magic' and spell.english == "Comet" then
        equip(sets.DarkAffinity)
    end
    if spell.skill == 'Elemental Magic' then
        if state.MagicBurst.value and spell.english ~= 'Death' then
            --if state.CastingMode.value == "Resistant" then
                --equip(sets.magic_burst.Resistant)
            --else
                equip(sets.magic_burst)
            --end
            if spell.english == "Impact" then
                equip(sets.midcast.Impact)
            end
        end
        if (spell.element == world.day_element or spell.element == world.weather_element) then
            equip(sets.Obi)
        end
    end
    if buffactive['Mana Wall'] then
        equip(sets.precast.JA['Mana Wall'])
    end
	if spell.action_type == 'Magic' then
		if spell.english == 'Death' then
			if world.weather_element == 'Dark' or world.day_element == 'Dark' then
				equip(sets.Obi)
			end
		end
	end
end`

The luzaf ring issue however is weird.  It will equip luzaf on double up but not any phantom rolls.

**Comment by druskey79** [comment]
I get 1290: attempt to call global 'handle_equipping_gear' (a nil value) when I load your cor lua.
