### ISSUE TITLE
DNC LUA

### ISSUE THREAD

**Issue by tmtrademark** [ArislanShiva/luas#2]
Hi there.

Been using your DNC Lua as a basis for my own, and wanted to let you know there's an issue with your haste sets, in case you use the same naming convention elsewhere.

When you add the haste string to the `classes.CustomMeleeGroups` object, you're appending it, but in your sets, you have the haste string first like this: `sets.engaged.MaxHaste.HighAcc`. These will never work because the haste value is appended to the end, so they should be `sets.engaged.HighAcc.MaxHaste`. Otherwise, a super solid lua, thanks for sharing.

**Comment by ArislanShiva** [comment]
Thanks for pointing the issue out.  Not sure how that happened. ><;
