### ISSUE TITLE
simple fix?

### ISSUE THREAD

**Issue by justmarccoff** [ArislanShiva/luas#3]
I am just trying to find a way to code gearswap to select a random number for lockstyle
send_command('input /macro book 15;wait .1;input /macro set 1;wait 2;input /lockstyleset 99'

is there a way to have it select a random number in a range IE 50-63
of select number IE 50,55,60 etc?

**Comment by ArislanShiva** [comment]
Haven't tested, but this should work:

`lockstyle =math.random(50,63)`
