### ISSUE TITLE
Arislan-COR.lua gear called from Arislan-Globals.lua but no include for Arislan-Globals.lua in Arislan-COR.lua?

### ISSUE THREAD

**Issue by Fett2** [ArislanShiva/luas#4]
I apologize for my newbieness, but I see in Arislan-COR.lua there is gear that is called from Arislan-Globals.lua however I don't see an include for that in Arislan-COR.lua. Is there another file Arislan-COR.lua includes which has the include for Arislan-Globals.lua?

**Comment by ArislanShiva** [comment]
Gearswap automatically detects yourname-Globals in the /data folder.
