### ISSUE TITLE
Having problems with the Windows key bindings you've emplemented

### ISSUE THREAD

**Issue by ShepardG** [ArislanShiva/luas#5]
Got everything working great (good job btw!) but I can't seem to get my windows key to function to enable thinks like "capacity points, luzaf ring, quickdraw mode" etc.  nor do the Utsusemi spells function as designed.   Do i need to configure my windows key a certain way outside of the game?  any help would be appreciated!  thanks in advance
-Shepard

**Comment by ArislanShiva** [comment]
There could be some native windows shortcuts that could use those same key combinations on your end.

You can either change the keybinds to something that doesn't use the windows key, or trigger the commands as a direct command:

`//gs c toggle CP`

or via in-game macro:

`/console c toggle CP`
