### ISSUE TITLE
Whm Lua

### ISSUE THREAD

**Issue by Miltani** [ArislanShiva/luas#9]
There seemed to be some issue with activating light arts and the associated scholar commands.
In the older version, it seemed that there was a bind command to activate them but now they are all just status cycle

**Comment by Miltani** [comment]
Realized that there are two job_self_command in the lua script  which is causing the problem, grouping them together solved it

**Comment by bo3esa** [comment]
and i think should use conserveMP set for raise/arise/RR, enhancing duration for storms
